import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedEvent = {
    title: string;
    slug: string;
    month: number;
    day: number;
    year?: number | null;
    type: "BIRTHDAY" | "ANNIVERSARY" | "MEME" | "FANDOM" | "HISTORY" | "BRAND";
    category:
        | "CELEBRITY"
        | "INFLUENCER"
        | "KPOP"
        | "ESPORTS"
        | "GAME"
        | "ANIME"
        | "MEME"
        | "BRAND"
        | "HISTORY"
        | "ETC";
    description: string;
    trustLevel: "OFFICIAL" | "SOURCE_VERIFIED" | "COMMUNITY" | "UNCERTAIN";
    sourceTitle: string;
    sourceUrl: string;
    sourceType: "OFFICIAL" | "NEWS" | "WIKI" | "COMMUNITY" | "SNS";
    tags: string[];
};

const events: SeedEvent[] = [
    {
        title: "페이커 생일",
        slug: "faker-birthday-5-7",
        month: 5,
        day: 7,
        year: 1996,
        type: "BIRTHDAY",
        category: "ESPORTS",
        description: "리그 오브 레전드 프로게이머 페이커의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Faker",
        sourceUrl: "https://en.wikipedia.org/wiki/Faker_(gamer)",
        sourceType: "WIKI",
        tags: ["생일", "e스포츠", "LoL"],
    },
    {
        title: "데프트 생일",
        slug: "deft-birthday-10-23",
        month: 10,
        day: 23,
        year: 1996,
        type: "BIRTHDAY",
        category: "ESPORTS",
        description: "리그 오브 레전드 프로게이머 데프트의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Deft",
        sourceUrl: "https://en.wikipedia.org/wiki/Deft_(gamer)",
        sourceType: "WIKI",
        tags: ["생일", "e스포츠", "LoL"],
    },
    {
        title: "쵸비 생일",
        slug: "chovy-birthday-3-3",
        month: 3,
        day: 3,
        year: 2001,
        type: "BIRTHDAY",
        category: "ESPORTS",
        description: "리그 오브 레전드 프로게이머 쵸비의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Chovy",
        sourceUrl: "https://en.wikipedia.org/wiki/Chovy",
        sourceType: "WIKI",
        tags: ["생일", "e스포츠", "LoL"],
    },
    {
        title: "쇼메이커 생일",
        slug: "showmaker-birthday-7-22",
        month: 7,
        day: 22,
        year: 2000,
        type: "BIRTHDAY",
        category: "ESPORTS",
        description: "리그 오브 레전드 프로게이머 쇼메이커의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - ShowMaker",
        sourceUrl: "https://en.wikipedia.org/wiki/ShowMaker",
        sourceType: "WIKI",
        tags: ["생일", "e스포츠", "LoL"],
    },
    {
        title: "룰러 생일",
        slug: "ruler-birthday-12-29",
        month: 12,
        day: 29,
        year: 1998,
        type: "BIRTHDAY",
        category: "ESPORTS",
        description: "리그 오브 레전드 프로게이머 룰러의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Ruler",
        sourceUrl: "https://en.wikipedia.org/wiki/Ruler_(gamer)",
        sourceType: "WIKI",
        tags: ["생일", "e스포츠", "LoL"],
    },
    {
        title: "케리아 생일",
        slug: "keria-birthday-10-14",
        month: 10,
        day: 14,
        year: 2002,
        type: "BIRTHDAY",
        category: "ESPORTS",
        description: "리그 오브 레전드 프로게이머 케리아의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Keria",
        sourceUrl: "https://en.wikipedia.org/wiki/Keria",
        sourceType: "WIKI",
        tags: ["생일", "e스포츠", "LoL"],
    },
    {
        title: "RM 생일",
        slug: "rm-birthday-9-12",
        month: 9,
        day: 12,
        year: 1994,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BTS 멤버 RM의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - RM",
        sourceUrl: "https://en.wikipedia.org/wiki/RM_(musician)",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BTS"],
    },
    {
        title: "진 생일",
        slug: "jin-birthday-12-4",
        month: 12,
        day: 4,
        year: 1992,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BTS 멤버 진의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Jin",
        sourceUrl: "https://en.wikipedia.org/wiki/Jin_(singer)",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BTS"],
    },
    {
        title: "슈가 생일",
        slug: "suga-birthday-3-9",
        month: 3,
        day: 9,
        year: 1993,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BTS 멤버 슈가의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Suga",
        sourceUrl: "https://en.wikipedia.org/wiki/Suga",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BTS"],
    },
    {
        title: "제이홉 생일",
        slug: "j-hope-birthday-2-18",
        month: 2,
        day: 18,
        year: 1994,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BTS 멤버 제이홉의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - J-Hope",
        sourceUrl: "https://en.wikipedia.org/wiki/J-Hope",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BTS"],
    },
    {
        title: "지민 생일",
        slug: "jimin-birthday-10-13",
        month: 10,
        day: 13,
        year: 1995,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BTS 멤버 지민의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Jimin",
        sourceUrl: "https://en.wikipedia.org/wiki/Jimin",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BTS"],
    },
    {
        title: "뷔 생일",
        slug: "v-birthday-12-30",
        month: 12,
        day: 30,
        year: 1995,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BTS 멤버 뷔의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - V",
        sourceUrl: "https://en.wikipedia.org/wiki/V_(singer)",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BTS"],
    },
    {
        title: "정국 생일",
        slug: "jungkook-birthday-9-1",
        month: 9,
        day: 1,
        year: 1997,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BTS 멤버 정국의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Jungkook",
        sourceUrl: "https://en.wikipedia.org/wiki/Jungkook",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BTS"],
    },
    {
        title: "아이유 생일",
        slug: "iu-birthday-5-16",
        month: 5,
        day: 16,
        year: 1993,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "가수 겸 배우 아이유의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - IU",
        sourceUrl: "https://en.wikipedia.org/wiki/IU_(singer)",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "가수"],
    },
    {
        title: "태연 생일",
        slug: "taeyeon-birthday-3-9",
        month: 3,
        day: 9,
        year: 1989,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "소녀시대 멤버 태연의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Taeyeon",
        sourceUrl: "https://en.wikipedia.org/wiki/Taeyeon",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "소녀시대"],
    },
    {
        title: "지드래곤 생일",
        slug: "g-dragon-birthday-8-18",
        month: 8,
        day: 18,
        year: 1988,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "가수 지드래곤의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - G-Dragon",
        sourceUrl: "https://en.wikipedia.org/wiki/G-Dragon",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BIGBANG"],
    },
    {
        title: "제니 생일",
        slug: "jennie-birthday-1-16",
        month: 1,
        day: 16,
        year: 1996,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BLACKPINK 멤버 제니의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Jennie",
        sourceUrl: "https://en.wikipedia.org/wiki/Jennie_(singer)",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BLACKPINK"],
    },
    {
        title: "지수 생일",
        slug: "jisoo-birthday-1-3",
        month: 1,
        day: 3,
        year: 1995,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BLACKPINK 멤버 지수의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Jisoo",
        sourceUrl: "https://en.wikipedia.org/wiki/Jisoo",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BLACKPINK"],
    },
    {
        title: "로제 생일",
        slug: "rose-birthday-2-11",
        month: 2,
        day: 11,
        year: 1997,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BLACKPINK 멤버 로제의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Rosé",
        sourceUrl: "https://en.wikipedia.org/wiki/Ros%C3%A9",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BLACKPINK"],
    },
    {
        title: "리사 생일",
        slug: "lisa-birthday-3-27",
        month: 3,
        day: 27,
        year: 1997,
        type: "BIRTHDAY",
        category: "KPOP",
        description: "BLACKPINK 멤버 리사의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Lisa",
        sourceUrl: "https://en.wikipedia.org/wiki/Lisa_(rapper)",
        sourceType: "WIKI",
        tags: ["생일", "KPOP", "BLACKPINK"],
    },
    {
        title: "테일러 스위프트 생일",
        slug: "taylor-swift-birthday-12-13",
        month: 12,
        day: 13,
        year: 1989,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "미국 싱어송라이터 테일러 스위프트의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Taylor Swift",
        sourceUrl: "https://en.wikipedia.org/wiki/Taylor_Swift",
        sourceType: "WIKI",
        tags: ["생일", "해외연예인", "음악"],
    },
    {
        title: "아리아나 그란데 생일",
        slug: "ariana-grande-birthday-6-26",
        month: 6,
        day: 26,
        year: 1993,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "미국 가수 아리아나 그란데의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Ariana Grande",
        sourceUrl: "https://en.wikipedia.org/wiki/Ariana_Grande",
        sourceType: "WIKI",
        tags: ["생일", "해외연예인", "음악"],
    },
    {
        title: "빌리 아일리시 생일",
        slug: "billie-eilish-birthday-12-18",
        month: 12,
        day: 18,
        year: 2001,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "미국 싱어송라이터 빌리 아일리시의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Billie Eilish",
        sourceUrl: "https://en.wikipedia.org/wiki/Billie_Eilish",
        sourceType: "WIKI",
        tags: ["생일", "해외연예인", "음악"],
    },
    {
        title: "브루노 마스 생일",
        slug: "bruno-mars-birthday-10-8",
        month: 10,
        day: 8,
        year: 1985,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "미국 싱어송라이터 브루노 마스의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Bruno Mars",
        sourceUrl: "https://en.wikipedia.org/wiki/Bruno_Mars",
        sourceType: "WIKI",
        tags: ["생일", "해외연예인", "음악"],
    },
    {
        title: "드레이크 생일",
        slug: "drake-birthday-10-24",
        month: 10,
        day: 24,
        year: 1986,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "캐나다 래퍼 겸 가수 드레이크의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Drake",
        sourceUrl: "https://en.wikipedia.org/wiki/Drake_(musician)",
        sourceType: "WIKI",
        tags: ["생일", "해외연예인", "음악"],
    },
    {
        title: "셀레나 고메즈 생일",
        slug: "selena-gomez-birthday-7-22",
        month: 7,
        day: 22,
        year: 1992,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "미국 배우 겸 가수 셀레나 고메즈의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Selena Gomez",
        sourceUrl: "https://en.wikipedia.org/wiki/Selena_Gomez",
        sourceType: "WIKI",
        tags: ["생일", "해외연예인", "음악"],
    },
    {
        title: "저스틴 비버 생일",
        slug: "justin-bieber-birthday-3-1",
        month: 3,
        day: 1,
        year: 1994,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "캐나다 가수 저스틴 비버의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Justin Bieber",
        sourceUrl: "https://en.wikipedia.org/wiki/Justin_Bieber",
        sourceType: "WIKI",
        tags: ["생일", "해외연예인", "음악"],
    },
    {
        title: "크리스티아누 호날두 생일",
        slug: "cristiano-ronaldo-birthday-2-5",
        month: 2,
        day: 5,
        year: 1985,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "축구 선수 크리스티아누 호날두의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Cristiano Ronaldo",
        sourceUrl: "https://en.wikipedia.org/wiki/Cristiano_Ronaldo",
        sourceType: "WIKI",
        tags: ["생일", "스포츠", "축구"],
    },
    {
        title: "리오넬 메시 생일",
        slug: "lionel-messi-birthday-6-24",
        month: 6,
        day: 24,
        year: 1987,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "축구 선수 리오넬 메시의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Lionel Messi",
        sourceUrl: "https://en.wikipedia.org/wiki/Lionel_Messi",
        sourceType: "WIKI",
        tags: ["생일", "스포츠", "축구"],
    },
    {
        title: "마이클 조던 생일",
        slug: "michael-jordan-birthday-2-17",
        month: 2,
        day: 17,
        year: 1963,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "농구 선수 마이클 조던의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Michael Jordan",
        sourceUrl: "https://en.wikipedia.org/wiki/Michael_Jordan",
        sourceType: "WIKI",
        tags: ["생일", "스포츠", "농구"],
    },
    {
        title: "르브론 제임스 생일",
        slug: "lebron-james-birthday-12-30",
        month: 12,
        day: 30,
        year: 1984,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "농구 선수 르브론 제임스의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - LeBron James",
        sourceUrl: "https://en.wikipedia.org/wiki/LeBron_James",
        sourceType: "WIKI",
        tags: ["생일", "스포츠", "농구"],
    },
    {
        title: "일론 머스크 생일",
        slug: "elon-musk-birthday-6-28",
        month: 6,
        day: 28,
        year: 1971,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "기업가 일론 머스크의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Elon Musk",
        sourceUrl: "https://en.wikipedia.org/wiki/Elon_Musk",
        sourceType: "WIKI",
        tags: ["생일", "기업가", "테크"],
    },
    {
        title: "스티브 잡스 생일",
        slug: "steve-jobs-birthday-2-24",
        month: 2,
        day: 24,
        year: 1955,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "애플 공동 창업자 스티브 잡스의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Steve Jobs",
        sourceUrl: "https://en.wikipedia.org/wiki/Steve_Jobs",
        sourceType: "WIKI",
        tags: ["생일", "기업가", "테크"],
    },
    {
        title: "빌 게이츠 생일",
        slug: "bill-gates-birthday-10-28",
        month: 10,
        day: 28,
        year: 1955,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "마이크로소프트 공동 창업자 빌 게이츠의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Bill Gates",
        sourceUrl: "https://en.wikipedia.org/wiki/Bill_Gates",
        sourceType: "WIKI",
        tags: ["생일", "기업가", "테크"],
    },
    {
        title: "마크 저커버그 생일",
        slug: "mark-zuckerberg-birthday-5-14",
        month: 5,
        day: 14,
        year: 1984,
        type: "BIRTHDAY",
        category: "CELEBRITY",
        description: "메타 공동 창업자 마크 저커버그의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Mark Zuckerberg",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Zuckerberg",
        sourceType: "WIKI",
        tags: ["생일", "기업가", "테크"],
    },
    {
        title: "미스터비스트 생일",
        slug: "mrbeast-birthday-5-7",
        month: 5,
        day: 7,
        year: 1998,
        type: "BIRTHDAY",
        category: "INFLUENCER",
        description: "유튜버 미스터비스트의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - MrBeast",
        sourceUrl: "https://en.wikipedia.org/wiki/MrBeast",
        sourceType: "WIKI",
        tags: ["생일", "인플루언서", "유튜브"],
    },
    {
        title: "퓨디파이 생일",
        slug: "pewdiepie-birthday-10-24",
        month: 10,
        day: 24,
        year: 1989,
        type: "BIRTHDAY",
        category: "INFLUENCER",
        description: "유튜버 퓨디파이의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - PewDiePie",
        sourceUrl: "https://en.wikipedia.org/wiki/PewDiePie",
        sourceType: "WIKI",
        tags: ["생일", "인플루언서", "유튜브"],
    },
    {
        title: "마키플라이어 생일",
        slug: "markiplier-birthday-6-28",
        month: 6,
        day: 28,
        year: 1989,
        type: "BIRTHDAY",
        category: "INFLUENCER",
        description: "유튜버 마키플라이어의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Markiplier",
        sourceUrl: "https://en.wikipedia.org/wiki/Markiplier",
        sourceType: "WIKI",
        tags: ["생일", "인플루언서", "유튜브"],
    },
    {
        title: "잭셉틱아이 생일",
        slug: "jacksepticeye-birthday-2-7",
        month: 2,
        day: 7,
        year: 1990,
        type: "BIRTHDAY",
        category: "INFLUENCER",
        description: "유튜버 잭셉틱아이의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Jacksepticeye",
        sourceUrl: "https://en.wikipedia.org/wiki/Jacksepticeye",
        sourceType: "WIKI",
        tags: ["생일", "인플루언서", "유튜브"],
    },
    {
        title: "나루토 생일",
        slug: "naruto-uzumaki-birthday-10-10",
        month: 10,
        day: 10,
        year: null,
        type: "FANDOM",
        category: "ANIME",
        description: "애니메이션 나루토의 캐릭터 우즈마키 나루토의 생일입니다.",
        trustLevel: "COMMUNITY",
        sourceTitle: "Naruto Wiki - Naruto Uzumaki",
        sourceUrl: "https://naruto.fandom.com/wiki/Naruto_Uzumaki",
        sourceType: "COMMUNITY",
        tags: ["캐릭터생일", "애니", "팬덤"],
    },
    {
        title: "몽키 D. 루피 생일",
        slug: "monkey-d-luffy-birthday-5-5",
        month: 5,
        day: 5,
        year: null,
        type: "FANDOM",
        category: "ANIME",
        description: "원피스의 캐릭터 몽키 D. 루피의 생일입니다.",
        trustLevel: "COMMUNITY",
        sourceTitle: "One Piece Wiki - Monkey D. Luffy",
        sourceUrl: "https://onepiece.fandom.com/wiki/Monkey_D._Luffy",
        sourceType: "COMMUNITY",
        tags: ["캐릭터생일", "애니", "팬덤"],
    },
    {
        title: "하츠네 미쿠 생일",
        slug: "hatsune-miku-birthday-8-31",
        month: 8,
        day: 31,
        year: null,
        type: "FANDOM",
        category: "ANIME",
        description: "보컬로이드 캐릭터 하츠네 미쿠의 기념일로 활용되는 날짜입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Hatsune Miku",
        sourceUrl: "https://en.wikipedia.org/wiki/Hatsune_Miku",
        sourceType: "WIKI",
        tags: ["캐릭터", "보컬로이드", "팬덤"],
    },
    {
        title: "해리 포터 생일",
        slug: "harry-potter-birthday-7-31",
        month: 7,
        day: 31,
        year: null,
        type: "FANDOM",
        category: "ETC",
        description: "해리 포터 시리즈의 주인공 해리 포터의 생일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Harry Potter",
        sourceUrl: "https://en.wikipedia.org/wiki/Harry_Potter_(character)",
        sourceType: "WIKI",
        tags: ["캐릭터생일", "팬덤", "소설"],
    },
    {
        title: "스타워즈 데이",
        slug: "star-wars-day-5-4",
        month: 5,
        day: 4,
        year: null,
        type: "FANDOM",
        category: "ETC",
        description: "스타워즈 팬덤에서 기념하는 대표적인 팬덤 기념일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Star Wars Day",
        sourceUrl: "https://en.wikipedia.org/wiki/Star_Wars_Day",
        sourceType: "WIKI",
        tags: ["팬덤", "기념일", "영화"],
    },
    {
        title: "파이 데이",
        slug: "pi-day-3-14",
        month: 3,
        day: 14,
        year: null,
        type: "ANNIVERSARY",
        category: "ETC",
        description: "원주율 파이를 기념하는 날입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Pi Day",
        sourceUrl: "https://en.wikipedia.org/wiki/Pi_Day",
        sourceType: "WIKI",
        tags: ["기념일", "수학", "밈"],
    },
    {
        title: "세계 이모지의 날",
        slug: "world-emoji-day-7-17",
        month: 7,
        day: 17,
        year: null,
        type: "ANNIVERSARY",
        category: "MEME",
        description: "이모지를 주제로 온라인에서 자주 활용되는 기념일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - World Emoji Day",
        sourceUrl: "https://en.wikipedia.org/wiki/World_Emoji_Day",
        sourceType: "WIKI",
        tags: ["기념일", "이모지", "SNS"],
    },
    {
        title: "만우절",
        slug: "april-fools-day-4-1",
        month: 4,
        day: 1,
        year: null,
        type: "ANNIVERSARY",
        category: "MEME",
        description: "농담과 장난 콘텐츠가 많이 올라오는 날입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - April Fools' Day",
        sourceUrl: "https://en.wikipedia.org/wiki/April_Fools%27_Day",
        sourceType: "WIKI",
        tags: ["기념일", "밈", "SNS"],
    },
    {
        title: "어스 데이",
        slug: "earth-day-4-22",
        month: 4,
        day: 22,
        year: null,
        type: "ANNIVERSARY",
        category: "ETC",
        description: "환경 보호를 주제로 전 세계적으로 기념되는 날입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Earth Day",
        sourceUrl: "https://en.wikipedia.org/wiki/Earth_Day",
        sourceType: "WIKI",
        tags: ["기념일", "환경", "캠페인"],
    },
    {
        title: "국제 여성의 날",
        slug: "international-womens-day-3-8",
        month: 3,
        day: 8,
        year: null,
        type: "ANNIVERSARY",
        category: "HISTORY",
        description: "여성의 권리와 성평등을 기념하는 국제 기념일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - International Women's Day",
        sourceUrl: "https://en.wikipedia.org/wiki/International_Women%27s_Day",
        sourceType: "WIKI",
        tags: ["기념일", "역사", "사회"],
    },
    {
        title: "세계 물의 날",
        slug: "world-water-day-3-22",
        month: 3,
        day: 22,
        year: null,
        type: "ANNIVERSARY",
        category: "ETC",
        description: "물의 중요성과 물 문제를 알리기 위한 국제 기념일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - World Water Day",
        sourceUrl: "https://en.wikipedia.org/wiki/World_Water_Day",
        sourceType: "WIKI",
        tags: ["기념일", "환경", "캠페인"],
    },
    {
        title: "세계 책의 날",
        slug: "world-book-day-4-23",
        month: 4,
        day: 23,
        year: null,
        type: "ANNIVERSARY",
        category: "ETC",
        description: "독서와 출판, 저작권을 기념하는 날입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - World Book Day",
        sourceUrl: "https://en.wikipedia.org/wiki/World_Book_Day",
        sourceType: "WIKI",
        tags: ["기념일", "책", "문화"],
    },
    {
        title: "세계 음악의 날",
        slug: "world-music-day-6-21",
        month: 6,
        day: 21,
        year: null,
        type: "ANNIVERSARY",
        category: "ETC",
        description: "음악을 주제로 다양한 콘텐츠를 만들기 좋은 날입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - Fête de la Musique",
        sourceUrl: "https://en.wikipedia.org/wiki/F%C3%AAte_de_la_Musique",
        sourceType: "WIKI",
        tags: ["기념일", "음악", "문화"],
    },
    {
        title: "세계 동물의 날",
        slug: "world-animal-day-10-4",
        month: 10,
        day: 4,
        year: null,
        type: "ANNIVERSARY",
        category: "ETC",
        description: "동물 보호와 동물 복지를 주제로 하는 국제 기념일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - World Animal Day",
        sourceUrl: "https://en.wikipedia.org/wiki/World_Animal_Day",
        sourceType: "WIKI",
        tags: ["기념일", "동물", "캠페인"],
    },
    {
        title: "세계 정신 건강의 날",
        slug: "world-mental-health-day-10-10",
        month: 10,
        day: 10,
        year: null,
        type: "ANNIVERSARY",
        category: "ETC",
        description: "정신 건강에 대한 인식을 높이기 위한 국제 기념일입니다.",
        trustLevel: "SOURCE_VERIFIED",
        sourceTitle: "Wikipedia - World Mental Health Day",
        sourceUrl: "https://en.wikipedia.org/wiki/World_Mental_Health_Day",
        sourceType: "WIKI",
        tags: ["기념일", "건강", "캠페인"],
    },
];

async function main() {
    console.log(`Start seeding ${events.length} real draft events...`);

    for (const item of events) {
        const event = await prisma.event.upsert({
            where: {
                slug: item.slug,
            },
            update: {
                title: item.title,
                month: item.month,
                day: item.day,
                year: item.year ?? null,
                type: item.type,
                category: item.category,
                description: item.description,
                contentIdea: "",
                trustLevel: item.trustLevel,
                status: "DRAFT",
            },
            create: {
                title: item.title,
                slug: item.slug,
                month: item.month,
                day: item.day,
                year: item.year ?? null,
                type: item.type,
                category: item.category,
                description: item.description,
                contentIdea: "",
                trustLevel: item.trustLevel,
                status: "DRAFT",
            },
        });

        await prisma.source.deleteMany({
            where: {
                eventId: event.id,
            },
        });

        await prisma.source.create({
            data: {
                eventId: event.id,
                title: item.sourceTitle,
                url: item.sourceUrl,
                type: item.sourceType,
                verified:
                    item.trustLevel === "OFFICIAL" ||
                    item.trustLevel === "SOURCE_VERIFIED",
            },
        });

        await prisma.eventTag.deleteMany({
            where: {
                eventId: event.id,
            },
        });

        for (const tagName of item.tags) {
            const tag = await prisma.tag.upsert({
                where: {
                    name: tagName,
                },
                update: {},
                create: {
                    name: tagName,
                },
            });

            await prisma.eventTag.create({
                data: {
                    eventId: event.id,
                    tagId: tag.id,
                },
            });
        }
    }

    console.log("Seed real draft events completed.");
}

main()
    .catch((error) => {
        console.error(error);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });